en:
    created: "created"
    last_edited: "last edited"
    critics: "critics"
    hidden_warning_intro: "This post is"
    hidden_warning_hidden: "hidden"
    hidden_warning_outro: " because it is not ready to be public. You can read it and criticize me to help make it ready."
bg:
    created: "създадено"
    last_edited: "последна промяна"
    critics: "критици"
    hidden_warning_intro: "Тази публикация е"
    hidden_warning_hidden: "скрита"
    hidden_warning_outro: ", защото не е готова да бъде публична. Може да я прочетеш и да ме критикуваш, за да я подобря."
